# SPDX-FileCopyrightText: Contributors to openadr-gui<https://github.com/ElaadNL/openadr-gui>
#
# SPDX-License-Identifier: Apache-2.0

"""
Django settings for openadrgui project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import logging
import os
import re
import sys
from pathlib import Path

import django_stubs_ext
import environ
import requests

django_stubs_ext.monkeypatch()

logger = logging.getLogger(__name__)


def is_test_context() -> bool:
    """
    Return True when we're running tests.

    See https://github.com/pytest-dev/pytest/issues/9502
    """
    return "PYTEST_VERSION" in os.environ


def is_runtime_context() -> bool:
    """
    Return True when we're running the actual server (gunicorn/runserver) and must require runtime env vars.

    Important: management commands like `migrate` trigger Django system checks which import URLconfs and views.
    That means `apps.ready` is often True during migrations, so using `apps.ready` as a heuristic is unreliable.
    """
    argv0 = Path(sys.argv[0]).name
    # Type-checkers import settings but shouldn't require runtime secrets.
    if argv0 in {"mypy", "dmypy"}:
        return False
    if argv0 in {"manage.py", "django-admin", "django-admin.py"}:
        # Management commands should not require runtime-only secrets by default.
        # Opt-in the ones that are "server-like".
        command = sys.argv[1] if len(sys.argv) > 1 else ""

        return command in {"runserver", "run_huey"}

    # Gunicorn / WSGI / ASGI import path (not a Django management command)
    return True


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize env before reading the file
env = environ.Env(
    DEBUG=(bool, False),
    TZ=(str, environ.Env.NOTSET),
    SECRET_KEY=(str, environ.Env.NOTSET),
    API_URL=(str, environ.Env.NOTSET),
    SECURE_SSL_REDIRECT=(bool, False),
    # OAUTH
    OAUTH_CLIENT_ID=(str, environ.Env.NOTSET),
    OAUTH_CLIENT_SECRET=(str, environ.Env.NOTSET),
    OAUTH_TOKEN_ENDPOINT=(str, environ.Env.NOTSET),
    OAUTH_SCOPES=(str, None),
    # DB
    DB_NAME=(str, "PLEASESETDBNAME"),
    DB_USER=(str, "PLEASESETDBUSER"),
    DB_PASSWORD=(str, "PLEASESETDBPASSWORD"),
    DB_HOST=(str, "PLEASESETDBHOST"),
    DB_PORT=(str, "PLEASESETDBPORT"),
    # OIDC
    OIDC_RP_CLIENT_ID=(str, environ.Env.NOTSET),
    OIDC_RP_CLIENT_SECRET=(str, environ.Env.NOTSET),
    OIDC_OP_BASE_URL=(str, environ.Env.NOTSET),
    CSRF_TRUSTED_ORIGINS=(str, "https://localhost,http://localhost,http://localhost:8000"),
)

# Read environment file from two directories above BASE_DIR
# Does NOT overwrite existing environment variables
environ.Env.read_env(BASE_DIR.parent / ".env", overwrite=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

SECURE_SSL_REDIRECT = env("SECURE_SSL_REDIRECT")
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Setup Database Settings
DB_NAME = env("DB_NAME")
DB_USER = env("DB_USER")
DB_PASSWORD = env("DB_PASSWORD")
DB_HOST = env("DB_HOST")
DB_PORT = env("DB_PORT")

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
USE_I18N = True

USE_TZ = True

if is_test_context() or is_runtime_context():
    # Use Timezone env
    TIME_ZONE = env("TZ")
    OIDC_OP_AUTHORIZATION_ENDPOINT = "MOCK_AUTHORIZATION_ENDPOINT"
    OIDC_RP_CLIENT_ID = "MOCK_CLIENT_ID"
    OIDC_RP_CLIENT_SECRET = "MOCK_CLIENT_SECRET"  # noqa: S105 #nosec B105
    OIDC_OP_BASE_URL = "MOCK_OP_BASE_URL"

# Only require these when running the actual server
if is_runtime_context() and not is_test_context():
    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = env("SECRET_KEY")
    API_URL = env("API_URL")
    OAUTH_CLIENT_ID = env("OAUTH_CLIENT_ID")
    OAUTH_CLIENT_SECRET = env("OAUTH_CLIENT_SECRET")
    OAUTH_TOKEN_ENDPOINT = env("OAUTH_TOKEN_ENDPOINT")
    OAUTH_SCOPES = env("OAUTH_SCOPES").split(",") if env("OAUTH_SCOPES") else []
    OIDC_RP_CLIENT_ID = env("OIDC_RP_CLIENT_ID")
    OIDC_RP_CLIENT_SECRET = env("OIDC_RP_CLIENT_SECRET")
    OIDC_OP_BASE_URL = env("OIDC_OP_BASE_URL")

    OIDC_OP_CONFIG_URL = f"{OIDC_OP_BASE_URL}/.well-known/openid-configuration"

    try:
        response = requests.get(OIDC_OP_CONFIG_URL, timeout=5)
        response.raise_for_status()
        config = response.json()
    except Exception:  # noqa: BLE001
        config = {}

    OIDC_OP_AUTHORIZATION_ENDPOINT = config.get("authorization_endpoint", f"{OIDC_OP_BASE_URL}/authorize")
    OIDC_OP_TOKEN_ENDPOINT = config.get("token_endpoint", f"{OIDC_OP_BASE_URL}/token")
    OIDC_OP_USER_ENDPOINT = config.get("userinfo_endpoint", f"{OIDC_OP_BASE_URL}/userinfo")
    OIDC_OP_JWKS_ENDPOINT = config.get("jwks_uri", f"{OIDC_OP_BASE_URL}/jwks")

    LOGIN_URL = "oidc_authentication_init"
    LOGIN_REDIRECT_URL = "/"
    LOGOUT_REDIRECT_URL = "/logged_out/"

    # Configure signing algorithm to match provider (Azure AD uses RS256)
    OIDC_RP_SIGN_ALGO = "RS256"

    # Exempt URLs browser reload middleware from OIDC SessionRefresh middleware to prevent redirect loops
    # Also used in LoginRequiredMiddleware
    OIDC_EXEMPT_URLS = [
        re.compile(r"^/__reload__/"),
        re.compile(r"^/static/"),  # allow CSS, JS, images
        re.compile(r"^/favicon\.ico$"),  # allow favicon.ico
        re.compile(r"^/favicon/"),  # allow favicon/ path (if you use site.webmanifest etc.)
        re.compile(r"^/logged_out/$"),  # allow logged out page
        re.compile(r"^/login/$"),  # allow login page
    ]

    # https://github.com/mozilla/mozilla-django-oidc/issues/435#issuecomment-1036372844
    # Issue with datarace which gives errors about the OIDCS state. Recommended fix is using cache session engine,
    #  but this is annoying for development. Revert back if issues arise.
    # SESSION_ENGINE = "django.contrib.sessions.backends.cache"  # noqa: ERA001
    SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"


ALLOWED_HOSTS = ["*"]

# Compress static files

COMPRESS_ENABLED = True

CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS").split(",")

BREADCRUMBS_TEMPLATE = "view_breadcrumbs/daisyui.html"
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "mozilla_django_oidc",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "view_breadcrumbs",
    "django_browser_reload",
    "django_cotton.apps.SimpleAppConfig",
    "template_partials.apps.SimpleAppConfig",
    "huey.contrib.djhuey",
    "django_htmx",
    "widget_tweaks",
    "compressor",
    "lockmgr",
    "huey_django_orm",
    "openadrgui",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "compression_middleware.middleware.CompressionMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    "mozilla_django_oidc.middleware.SessionRefresh",
    "openadrgui.middleware.LoginRequiredMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "openadrgui.middleware.HtmxBoostedMiddleware",
    "openadrgui.middleware.HtmxMessagesMiddleware",
    "openadrgui.middleware.HtmxErrorMiddleware",
]

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Configure Huey. See https://huey.readthedocs.io/en/latest/contrib.html#setting-things-up
HUEY = {
    # See https://github.com/avryhof/huey_django_orm
    "huey_class": "huey_django_orm.storage.DjangoORMHuey",  # Huey implementation to use.
    "name": DB_NAME,  # Use db name for huey.
    "results": True,  # Store return values of tasks.
    "store_none": True,  # If a task returns None, save to results.
    "immediate": False,  # If DEBUG=True, run synchronously.
    "consumer": {
        "workers": 1,
        "worker_type": "thread",
        "initial_delay": 0.1,  # Smallest polling interval, same as -d.
        "backoff": 1.15,  # Exponential backoff using this rate, -b.
        "max_delay": 10.0,  # Max possible polling interval, -m.
        "scheduler_interval": 1,  # Check schedule every second, -s.
        "periodic": True,  # Enable crontab feature.
        "check_worker_health": True,  # Enable worker health checks.
        "health_check_interval": 5,  # Check worker health every second.
    },
}

ROOT_URLCONF = "openadrgui.urls"

AUTHENTICATION_BACKENDS = [
    "openadrgui.auth_backend.PatchedOIDCAuthenticationBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# See https://django-cotton.com/docs/django-template-partials
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "OPTIONS": {
            "loaders": [
                (
                    "template_partials.loader.Loader",
                    [
                        (
                            "django.template.loaders.cached.Loader",
                            [
                                "django_cotton.cotton_loader.Loader",
                                "django.template.loaders.filesystem.Loader",
                                "django.template.loaders.app_directories.Loader",
                            ],
                        ),
                    ],
                ),
            ],
            "builtins": [
                "django_cotton.templatetags.cotton",
                "template_partials.templatetags.partials",
            ],
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "openadrgui.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

STATICFILES_DIRS = [BASE_DIR / "openadrgui" / "static"]

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    # other finders..
    "compressor.finders.CompressorFinder",
)


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST handlers
REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
}

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "debug.log",
            "backupCount": 2,
            "maxBytes": 1024 * 1024 * 5,  # 5MB
            "formatter": "verbose",
        },
    },
    "loggers": {
        "openadrgui": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "mozilla_django_oidc": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# File Upload Settings
FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.MemoryFileUploadHandler",  # Handle small files in memory
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",  # Fall back to disk for large files
]
FILE_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024 * 1024  # 500MB - keep more files in memory
