# SPDX-FileCopyrightText: Contributors to openadr-gui<https://github.com/ElaadNL/openadr-gui>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 5.2.5 on 2025-08-15 08:33

import django.db.models.deletion
import openadrgui.models.djangomodels
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.CharField(help_text="Configuration key", max_length=100, unique=True)),
                ("value", models.TextField(help_text="Configuration value")),
                (
                    "section",
                    models.CharField(help_text="Configuration section (e.g., General, OpenADR)", max_length=50),
                ),
                ("description", models.CharField(help_text="Description of this configuration", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("section", "key"),
            },
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.CharField(
                        choices=[("DEBUG", "Debug"), ("INFO", "Info"), ("WARNING", "Warning"), ("ERROR", "Error")],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("GUI", "GUI Action"),
                            ("OPENADR", "OpenADR Protocol"),
                            ("EVENT", "OpenADR Event"),
                            ("SYSTEM", "System"),
                        ],
                        default="SYSTEM",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("action", models.CharField(blank=True, default="", max_length=50)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("VEN", "VEN"),
                            ("PROGRAM", "Program"),
                            ("CONFIGURATION", "Configuration"),
                            ("EVENT", "Event"),
                            ("USER_LOGIN", "User login"),
                        ],
                        default="VEN",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("event_id", models.CharField(blank=True, default="", max_length=100)),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="DjangoProgramModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("program_name", openadrgui.models.djangomodels.NullCharField(max_length=100)),
                ("program_long_name", openadrgui.models.djangomodels.NullCharField(max_length=255, null=True)),
                ("retailer_name", openadrgui.models.djangomodels.NullCharField(max_length=100, null=True)),
                ("retailer_long_name", openadrgui.models.djangomodels.NullCharField(max_length=255, null=True)),
                ("program_type", openadrgui.models.djangomodels.NullCharField(max_length=100, null=True)),
                ("country", openadrgui.models.djangomodels.NullCharField(max_length=100, null=True)),
                ("principal_subdivision", openadrgui.models.djangomodels.NullCharField(max_length=100, null=True)),
                (
                    "interval_period",
                    openadrgui.models.djangomodels.JSONField(
                        decoder=openadrgui.models.djangomodels.JSONDecoder,
                        encoder=openadrgui.models.djangomodels.JSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "program_descriptions",
                    openadrgui.models.djangomodels.JSONField(
                        decoder=openadrgui.models.djangomodels.JSONDecoder,
                        encoder=openadrgui.models.djangomodels.JSONEncoder,
                        null=True,
                    ),
                ),
                ("binding_events", models.BooleanField(default=False)),
                ("local_price", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": (
                    "id",
                    "program_name",
                    "program_long_name",
                    "retailer_name",
                    "retailer_long_name",
                    "program_type",
                    "program_descriptions",
                    "binding_events",
                    "local_price",
                ),
                "constraints": [models.UniqueConstraint(fields=("program_name",), name="program_name_unique")],
            },
        ),
        migrations.CreateModel(
            name="DjangoEventModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_name", openadrgui.models.djangomodels.NullCharField(max_length=100, null=True)),
                (
                    "interval_period",
                    openadrgui.models.djangomodels.JSONField(
                        decoder=openadrgui.models.djangomodels.JSONDecoder,
                        encoder=openadrgui.models.djangomodels.JSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "intervals",
                    openadrgui.models.djangomodels.JSONField(
                        decoder=openadrgui.models.djangomodels.JSONDecoder,
                        encoder=openadrgui.models.djangomodels.JSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "targets",
                    openadrgui.models.djangomodels.JSONField(
                        decoder=openadrgui.models.djangomodels.JSONDecoder,
                        encoder=openadrgui.models.djangomodels.JSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "payload_descriptors",
                    openadrgui.models.djangomodels.JSONField(
                        decoder=openadrgui.models.djangomodels.JSONDecoder,
                        encoder=openadrgui.models.djangomodels.JSONEncoder,
                        null=True,
                    ),
                ),
                ("priority", models.IntegerField(null=True)),
                (
                    "program_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="openadrgui.djangoprogrammodel"),
                ),
            ],
            options={
                "ordering": ("id", "program_id", "event_name", "priority"),
                "constraints": [
                    models.UniqueConstraint(fields=("program_id", "event_name"), name="program_id_event_name_unique")
                ],
            },
        ),
    ]
