# SPDX-FileCopyrightText: Contributors to openadr-gui<https://github.com/ElaadNL/openadr-gui>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 5.2.6 on 2025-10-14 14:07

import django.core.validators
import django.db.models.deletion
import openadrgui.models.djangomodels
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openadrgui", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoResourceModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "resource_name",
                    openadrgui.models.djangomodels.NullCharField(
                        max_length=100, validators=[django.core.validators.MinLengthValidator(1)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramDeploymentLogModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("deployment_date", models.DateTimeField()),
                (
                    "deployment_status",
                    models.CharField(
                        choices=[("FAILED", "Failed"), ("IN_PROGRESS", "In Progress"), ("SUCCESS", "Success")],
                        default="IN_PROGRESS",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramDeploymentsModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("repeat", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Configuration",
        ),
        migrations.AlterField(
            model_name="logentry",
            name="details",
            field=openadrgui.models.djangomodels.JSONField(
                blank=True,
                decoder=openadrgui.models.djangomodels.JSONDecoder,
                default=dict,
                encoder=openadrgui.models.djangomodels.JSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="type",
            field=models.CharField(
                choices=[
                    ("VEN", "VEN"),
                    ("PROGRAM", "Program"),
                    ("CONFIGURATION", "Configuration"),
                    ("EVENT", "Event"),
                    ("USER_LOGIN", "User login"),
                    ("RESOURCE", "Resource"),
                ],
                default="VEN",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="djangoresourcemodel",
            constraint=models.UniqueConstraint(fields=("resource_name",), name="resource_name_unique"),
        ),
        migrations.AddField(
            model_name="programdeploymentsmodel",
            name="program",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="openadrgui.djangoprogrammodel"),
        ),
        migrations.AddField(
            model_name="programdeploymentlogmodel",
            name="program_deployment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="openadrgui.programdeploymentsmodel"
            ),
        ),
        migrations.AddConstraint(
            model_name="programdeploymentsmodel",
            constraint=models.UniqueConstraint(fields=("program", "repeat"), name="program_repeat_unique"),
        ),
        migrations.AddConstraint(
            model_name="programdeploymentlogmodel",
            constraint=models.UniqueConstraint(
                fields=("program_deployment", "deployment_date", "deployment_status"),
                name="program_deployment_date_status_unique",
            ),
        ),
    ]
