# SPDX-FileCopyrightText: Contributors to openadr-gui<https://github.com/ElaadNL/openadr-gui>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 5.2.6 on 2025-10-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openadrgui", "0002_djangoresourcemodel_programdeploymentlogmodel_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="programdeploymentsmodel",
            name="program_repeat_unique",
        ),
        migrations.RemoveField(
            model_name="programdeploymentsmodel",
            name="repeat",
        ),
        migrations.AddConstraint(
            model_name="programdeploymentsmodel",
            constraint=models.UniqueConstraint(fields=("program",), name="program_unique"),
        ),
    ]
