# SPDX-FileCopyrightText: Contributors to openadr-gui<https://github.com/ElaadNL/openadr-gui>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 5.2.6 on 2025-11-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openadrgui", "0003_remove_programdeploymentsmodel_program_repeat_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programdeploymentlogmodel",
            name="deployment_error_message",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="programdeploymentlogmodel",
            name="deployment_status",
            field=models.CharField(
                choices=[
                    ("FAILED", "Failed"),
                    ("SKIPPED", "Skipped"),
                    ("IN_PROGRESS", "In Progress"),
                    ("SUCCESS", "Success"),
                ],
                default="IN_PROGRESS",
            ),
        ),
    ]
